variables:
    - &file caddy/Containerfile
    - &repo codeberg.org/${CI_REPO_OWNER}/caddy

pipeline:
    build:
        image: woodpeckerci/plugin-docker-buildx
        settings:
            dockerfile: *file
            platforms: linux/amd64
            repo: *repo
            registry: codeberg.org
            tags: latest
            username: ${CI_REPO_OWNER}
            password:
                from_secret: oci_token
