name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build_cargo:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
