baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Example'
theme = "hugo-theme-arc"
themesDir = "../.."
paginate = 10
enableRobotsTXT = true
copyright = 'CC'

[params]
description = "test site"
index_list = false

[params.author]
name = 'the author'

[[params.links]]
text = "xtex"
url = "https://xtexx.eu.org/"
target = "_blank"

[[params.links]]
text = "about"
url = "/about"

[[params.links]]
text = "posts"
url = "/posts"

[[params.links]]
text = "archives"
url = "/archives"

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5
