#!/usr/bin/env bash

set -eux

EXOGIT_USER=$(id -un)

zigbuild() {
    distrobox enter archlinux -- fish -c "cargo zigbuild --target \"$1\" --bins --release"
}

checksums() {
    local -a execfiles
    readarray -d '' execfiles < <(find target/"$1"/release -maxdepth 1 -name 'wezen-*' -executable -printf '%f\0')
    pushd target/"$1"/release
    sha256sum "${execfiles[@]}" >sha256sum.txt
    popd
}

uploadbins() {
    curl --user "$EXOGIT_USER":"$EXOGIT_TOKEN" \
        -X DELETE \
        https://git.exozy.me/api/packages/"$EXOGIT_USER"/generic/wezen/dev-"$2"
    curl --user "$EXOGIT_USER":"$EXOGIT_TOKEN" \
        --upload-file target/"$1"/release/sha256sum.txt \
        https://git.exozy.me/api/packages/"$EXOGIT_USER"/generic/wezen/dev-"$2"/sha256sum.txt

    while IFS= read -r -d '' file; do
        curl --user "$EXOGIT_USER":"$EXOGIT_TOKEN" \
            --upload-file "$file" \
            https://git.exozy.me/api/packages/"$EXOGIT_USER"/generic/wezen/dev-"$2"/"$(basename "$file")"
    done < <(find target/"$1"/release -maxdepth 1 -name 'wezen-*' -executable -print0)
}

buildoci() {
    podman build --platform "$2" --manifest=git.exozy.me/"$EXOGIT_USER"/wezen:dev --build-arg=TARGETDIR="$1" --no-cache .
}

podman manifest rm git.exozy.me/"$EXOGIT_USER"/wezen:dev || true

zigbuild x86_64-unknown-linux-gnu
checksums x86_64-unknown-linux-gnu
uploadbins x86_64-unknown-linux-gnu amd64
buildoci x86_64-unknown-linux-gnu linux/amd64

zigbuild aarch64-unknown-linux-gnu
checksums aarch64-unknown-linux-gnu
uploadbins aarch64-unknown-linux-gnu aarch64
# buildoci aarch64-unknown-linux-gnu linux/arm64

podman manifest push git.exozy.me/"$EXOGIT_USER"/wezen:dev
