apiVersion: v1
kind: Pod
metadata:
    labels:
        app: caddy
    name: caddy
spec:
    containers:
        - image: docker.io/library/caddy:2.7.4-alpine
          name: caddy
          ports:
              - containerPort: 8080
                hostPort: 8080
              - containerPort: 80
                hostPort: 8081
          volumeMounts:
              - mountPath: /etc/caddy/
                name: caddy-config
    volumes:
        - hostPath:
              path: <% $CADDY_DIR %>
              type: Directory
          name: caddy-config
