branches: main

variables:
  - &file Containerfile
  - &repo codeberg.org/xtex-vnet/spica

pipeline:
  deploy:
    image: alpine
    commands:
      - echo "$SSH_KEY" >> ssh_key
      - chmod 0600 ssh_key
      - export SSH="ssh -i ssh_key -o StrictHostKeyChecking=no salt-master-cd@salt.infra.xvnet.eu.org"
      - apk add openssh-client-default
      - $SSH sudo salt-run state.orch orch.deploy
    secrets: [ssh_key]
