steps:
    build:
        image: bash
        commands:
            - git describe --long --always | tr -d '\n' > src/version.txt
            - podman build --force-rm --squash --tag localhost/home-new .
            - export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
            - systemctl --user stop xtex-home.service
            - podman image rm -f localhost/home
            - podman image tag localhost/home-new localhost/home
            - podman image untag localhost/home-new localhost/home-new
            - systemctl --user start xtex-home.service
#            - podman run --name home
#              --replace --detach
#              --memory 16m
#              --mount type=bind,source=/home/xtex/home,destination=/srv/run
#              --mount type=bind,source=/srv/http/xtex,destination=/srv/blog
#              --mount type=bind,source=/srv/http,destination=/srv/exopages
#              --env "UDS_DIR=exopages" --env "UDS_SUFFIX="
#              localhost/home
