branches: main

variables:
  - &file Containerfile
  - &repo codeberg.org/xtex-vnet/mekbuda

pipeline:
  rust-build:
    image: rust
    group: build
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default nightly
      - cargo check
      - cargo test

  container-push:
    image: woodpeckerci/plugin-docker-buildx
    group: build
    settings:
      dockerfile: *file
      platforms: linux/arm64/v8,linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: oci_token
    when:
      event: push
