matrix:
  VERSION:
    - 2.0.12
    - 2.13
    - 3.0-alpha1
    - &latest 3.0-alpha2
    - latest

pipeline:
  container-build:
    image: woodpeckerci/plugin-docker-buildx
    group: build
    settings:
      dockerfile: Containerfile
      dry_run: true
      repo: codeberg.org/xvnet/bird
      tags: latest
      build_args:
        LATEST: *latest

  container-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Containerfile
      platforms: linux/arm64/v8,linux/amd64
      repo: codeberg.org/xvnet/bird
      registry: codeberg.org
      tags:
        - ${VERSION}
      build_args:
        VERSION: ${VERSION}
        LATEST: *latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: oci_token
    when:
      event: push
