steps:
    build:
        image: bash
        commands:
            - git describe --long --always | tr -d '\n' > src/version.txt
            - podman build --force-rm --squash --tag localhost/home .
            - export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
            - systemctl --user restart xtex-home.service
            - podman image prune -f
#            - podman run --name home
#              --replace --detach
#              --memory 16m
#              --mount type=bind,source=/home/xtex/home,destination=/srv/run
#              --mount type=bind,source=/srv/http/xtex,destination=/srv/blog
#              --mount type=bind,source=/srv/http,destination=/srv/exopages
#              --env "UDS_DIR=exopages" --env "UDS_SUFFIX="
#              localhost/home

when:
    - branch: main
