pipeline:
    build:
        image: bash
        commands:
            - git describe --all --long --always | tr -d '\n' > src/version.txt
            - podman build --force-rm --squash --tag exozy.me/xtex/home .
            - podman run --name home
              --replace --restart unless-stopped --detach
              --memory 16m
              --mount type=bind,source=/home/xtex/home,destination=/srv/run
              --mount type=bind,source=/srv/http/pages/xtex,destination=/srv/blog
              --mount type=bind,source=/srv/http/pages,destination=/srv/exopages
              --env "UDS_DIR=exopages"
              exozy.me/xtex/home
