pipeline:
    build:
        image: bash
        commands:
            - git describe --all --long --always > src/static/version.txt
            - podman build --force-rm --squash --tag exozy.me/xtex/home .
            - podman run --name home
              --replace --restart on-failure:5 --detach
              --memory 64m
              --mount type=bind,source=/home/xtex/home,destination=/srv/run
              --mount type=bind,source=/srv/http/pages/xtex,destination=/srv/blog
              exozy.me/xtex/home
