[package]
name = "podrc"
version = "0.1.0"
edition = "2021"
description = "Manage podman resources with toml files"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.1", features = ["derive"] }
futures = "0.3.28"
notify = "6.0.0"
podman-api = "0.10.0"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.7.4"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json"] }
