[package]
name = "build-clean"
version = "1.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Clean all build caches on your disk!"
homepage = "https://codeberg.org/xtex/build-clean"
repository = "https://codeberg.org/xtex/build-clean.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
async-recursion = "1.0.4"
crossterm = "0.26.1"
cursive = { version = "0.20.0", features = ["crossterm-backend"] }
cursive-async-view = "0.6.0"
mlua = { version = "0.8.8", features = ["lua54", "send", "serde", "macros", "mlua_derive"] }
num_cpus = "1.15.0"
owo-colors = "3.5.0"
parking_lot = "0.12.1"
reqwest = { version = "0.11.17", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.0", features = ["full", "tracing"] }

[package.metadata.docs.rs]
features = ["mlua/vendored"]
rustdoc-args = ["--cfg", "docsrs"]
