[package]
name = "mekbuda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.70", features = ["backtrace"] }
bytes = "1.4.0"
futures-util = "0.3.27"
lazy_static = "1.4.0"
libc = "0.2.140"
reqwest = "0.11.15"
rtnetlink = "0.12.0"
serde = { version = "1.0.157", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tokio-tun = "0.7.0"
toml = "0.7.3"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.16", features = ["json"] }

[build-dependencies]
bindgen = "0.64.0"
