[package]
name = "wiki-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
chrono = "0.4.23"
log = "0.4.17"
mwapi_responses = "0.3.1"
mwbot = "0.4.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
simple_logger = "4.0.0"
tokio = { version = "1.25.0", features = ["full"] }

[[bin]]
name = "archive"
path = "src/maintaince/archive.rs"
