[package]
name = "build-clean"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
async-recursion = "1.0.4"
crates_io_api = "0.8.1"
crossterm = "0.26.1"
cursive = { version = "0.20.0", features = ["crossterm-backend"] }
cursive-async-view = "0.6.0"
mlua = { version = "0.8.8", features = ["lua54", "send", "serde", "macros", "mlua_derive"] }
num_cpus = "1.15.0"
parking_lot = "0.12.1"
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.28.0", features = ["full", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
