[package]
name = "spock"
version = "0.1.0"
edition = "2021"
authors = ["xtex"]
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.79"
parking_lot = "0.12.1"
reqwest = "0.11.23"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }
