[package]
name = "yjyz-tools"
description = "阳江一中实用工具"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.28.1"
egui = "0.28.1"
tokio = { version = "1.38.0", features = ["full"] }
xz2 = "0.1.7"

[dependencies.windows]
version = "0.58.0"
features = []

[build-dependencies]
winresource = "0.1.17"

[package.metadata.winresource]
OriginalFilename = "yjyz-tools.exe"
