[package]
name = "dn42-kb-canvas-wikipedia-rc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
bytes = "1.4.0"
flate2 = "1.0.25"
icmp-socket = "0.2.0"
image = { version = "0.24.5", default-features = false, features = ["bmp"] }
reqwest = "0.11.14"
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["full", "tracing"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["serde_json", "json"] }
