[package]
name = "yjyz-tools"
description = "阳江一中实用工具"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
eframe = "0.28.1"
egui = "0.28.1"
env_logger = "0.11.3"
log = { version = "0.4.22", features = ["std"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
tokio = { version = "1.38.0", features = ["full"] }
windows-registry = "0.2.0"
xz2 = "0.1.7"

[dependencies.windows]
version = "0.58.0"
features = []

[build-dependencies]
winresource = "0.1.17"

[package.metadata.winresource]
OriginalFilename = "yjyz-tools.exe"
