[package]
name = "yjyz-tools"
description = "阳江一中实用工具"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
cached = "0.52.0"
educe = "0.6.0"
eframe = "0.28.1"
egui = "0.28.1"
env_logger = "0.11.3"
log = { version = "0.4.22", features = ["std"] }
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
raw-window-handle = { version = "0.6.2", features = ["std"] }
sysinfo = "0.30.13"
tokio = { version = "1.38.0", features = ["full"] }
windows-registry = "0.2.0"
windows-targets = "0.52.6"
xz2 = "0.1.7"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
]

[build-dependencies]
winresource = "0.1.17"

[package.metadata.winresource]
OriginalFilename = "yjyz-tools.exe"
