targets = [
	{ triple = "x86_64-unknown-linux-musl" },
	{ triple = "wasm32-unknown-unknown" },
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
	"Apache-2.0",
	"MIT",
	"BSD-3-Clause",
	"ISC",
	"Unicode-DFS-2016",
	"OpenSSL",
	"MPL-2.0",
	"GPL-3.0",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
exceptions = []

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "allow"
wildcards = "allow"
deny = [
	{ name = "cmake" },
	# prefer rustls
	{ name = "openssl-sys" },
	{ name = "openssl" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
