name = "xtex's MP Pack"
author = "xtex"
version = "2.14.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1da35ca0f6085c99a856efbf084d8fdd2ef7270c429a15cdabd148f94a54f721"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
