name = "xtex's MP Pack"
author = "xtex"
version = "1.5.0"
description = "Minecraft modpack focusing on multiplayer (Survival, Creative or PvP) performance and experience optimization. "
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "944609d4c76f2537f3ad7fc382fd30358fec971fdbd22bbb51b55e8216a1068d"

[versions]
fabric = "0.14.14"
minecraft = "1.19.3"

[options]
acceptable_versions = ["1.19.2", "1.19.1", "1.19"]
