name = "xtex's MP Pack"
author = "xtex"
version = "2.14.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "145fb9b6b374bae947f0242f9bd958cd740ac86b3c5e68861426039396629178"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
