name = "xtex's MP Pack"
author = "xtex"
version = "1.2.0"
description = "Minecraft modpack focusing on multiplayer (Survival, Creative or PvP) performance and experience optimization. "
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58dcfc00d7b06ff2e33f519614d72b0923de3f220e9edb3d14aaaca1c7d14da8"

[versions]
fabric = "0.14.12"
minecraft = "1.19.3"

[options]
acceptable_versions = ["1.19.2", "1.19.1", "1.19"]
