name = "xtex's MP Pack"
author = "xtex"
version = "2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab3682953bc4ff8605ead74e79528f403bd6b6156d852a9b6140ac677378f721"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
