name = "xtex's MP Pack"
author = "xtex"
version = "2.14.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7187195e0171d9d885a05a94d943fc2c25c98cd397c4183bc93c3e00f609bdeb"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
