name = "xtex's MP Pack"
author = "xtex"
version = "2.14.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb332430abae69931dba1180bcb82784301640ff4c9ae95e10761522282f3ed6"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
