name = "xtex's MP Pack"
author = "xtex"
version = "2.15.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc58b90ff046260209b74325ce6e91cdea461bf5558a233d2a2c54683d944401"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
