name = "xtex's MP Pack"
author = "xtex"
version = "2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d10bc7fd5bf9f30eb9e9c7589f5911f8f14d8c8d16a1de5e99a2f26d769a6e8"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
