name = "xtex's MP Pack"
author = "xtex"
version = "2.15.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daf7280e7386b6c2f7ea2afbba244ec5e85b9a1b5e0075d98042aab79329d4c4"

[versions]
fabric = "0.16.0"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
