name = "xtex's MP Pack"
author = "xtex"
version = "2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d404d9adbdf037488f7eabbde4b108e9436a9186e708865471271aea85839941"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
