name = "xtex's MP Pack"
author = "xtex"
version = "2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c64bddcfe2252bc7c1f5be67e90ef8d9c5dada91ecc34b8008381a7075020e8"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
