name = "xtex's MP Pack"
author = "xtex"
version = "2.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ed9fdc574cb658f304cc5710d3a22623a77cae5cacd4b268c1cced075614dcf"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
