name = "xtex's MP Pack"
author = "xtex"
version = "2.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a3caf76836181ccd48cfa83d413becd5e675056532514816ef1c339d42748bf"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.2"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
