- name: Update Minion ID
  ansible.builtin.template:
    src: ../../../salt/minion_id.j2
    dest: /etc/salt/minion_id
    owner: root
    group: root
    mode: "0644"
    backup: false

- name: Update Minion config
  ansible.builtin.template:
    src: ../../../salt/minion.yaml.j2
    dest: /etc/salt/minion
    owner: root
    group: root
    mode: "0644"
    validate: bash -c "sudo systemctl restart salt-minion; sudo cp %s /dev/null"
    backup: false
