PATH="/home/xtex/.local/bin:$PATH"
GRADLE_USER_HOME="/opt/gradle"

RUSTUP_HOME="/opt/rustup"
CARGO_HOME="/opt/cargo"

SDKMAN_DIR="/opt/sdkman"

ZVM_INSTALL="/opt/zvm/self"
PATH="$PATH:/opt/zvm/bin:$ZVM_INSTALL"

GOROOT="/opt/go"
