[build]
target = "x86_64-pc-windows-gnu"
rustflags = [
    # avoid api-ms-win-core-winrt-error-l1-1-0.dll
    "--cfg=windows_slim_errors"
]

[profile.release]
opt-level = 3
lto = true
incremental = true
