[profile.release]
opt-level = "s"
lto = true
strip = "debuginfo"
codegen-units = 1

[target.x86_64-pc-windows-gnu]
rustflags = [
    # avoid api-ms-win-core-winrt-error-l1-1-0.dll
    "--cfg=windows_slim_errors",
    # use lld
    "-C",
    "link-arg=-fuse-ld=lld",
]
