[package]
name = "rauthy"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
postgres = []

[dependencies]
rauthy-common = { path = "../common" }
rauthy-error = { path = "../error" }
rauthy-handlers = { path = "../api" }
rauthy-middlewares = { path = "../middlewares" }
rauthy-models = { path = "../models" }
rauthy-schedulers = { path = "../schedulers" }
rauthy-service = { path = "../service" }

actix-web = { workspace = true }
actix-web-prom = { workspace = true }
actix-service = { workspace = true }
chrono = { workspace = true }
cryptr = { workspace = true }
dotenvy = { workspace = true }
flume = { workspace = true }
hiqlite = { workspace = true }
num_cpus = { workspace = true }
prometheus = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
rustls-pemfile = { workspace = true }
serde_json = { workspace = true }
spow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }

[dev-dependencies]
rauthy-api-types = { path = "../api_types" }

ed25519-compact = { workspace = true }
josekit = "0.8"
pretty_assertions = "1"
reqwest = { workspace = true }
ring = { workspace = true }
serde = "1"
tokio-test = "*"
