matrix:
    VERSION:
        - 2.14 # TAG:LATEST
        - 2.13.1
        - 2.13

steps:
    - name: build
      image: woodpeckerci/plugin-docker-buildx
      settings:
          platforms: linux/amd64,linux/arm64/v8
          repo: codeberg.org/${CI_REPO_OWNER}/bird
          registry: codeberg.org
          tags: ${VERSION}
          build_args:
              - "VERSION=${VERSION}"
          username: ${CI_REPO_OWNER}
          password:
              from_secret: codeberg_token
          dockerfile: bird/Containerfile
    - name: mark-latest
      image: alpine
      secrets: [codeberg_token]
      commands:
          - ./misc/tag-latest.sh "codeberg.org/${CI_REPO_OWNER}/bird" .woodpecker/bird.yaml "${VERSION}"
    - name: send-ntfy
      image: alpine
      secrets: [ntfy_token]
      environment:
          - "VERSION=${VERSION}"
      when:
          - status: [success, failure]
      commands:
          - ./misc/send-log.sh
when:
    - event: push
      path:
          include: [".woodpecker/bird.yaml", "bird/*"]
    - event: cron
      cron: build
    - event: manual
      evaluate: 'TARGET == "bird"'
