steps:
    build:
        image: alpine
        commands:
            - apk add bash make cmake clang llvm musl-dev coreutils binutils lld 
                bear doxygen cmd:envsubst grub grub-bios grub-efi cmd:xorriso cmd:mtools
            - make -j$(nproc) ARCH=x86 default doc

    publish:
        image: alpine
        commands:
            - apk add curl jo jq zstd tar

            - core_obj_url=$(curl -F'file=@out/core/core.o' https://envs.sh)
            - iso_url=$(curl -F'file=@out/arch/x86/distrib/iso/boot.iso' https://envs.sh)

            - tar -c --zstd -f doc-html.tar.zst out/doc/html/
            - doc_html_url=$(curl -F'file=@doc-html.tar.zst' https://envs.sh)

            - jo assets=$(jo core=$core_obj_url iso=$iso_url doc=$(jo html=$doc_html_url)) | jq > index.json
            - index_url=$(curl -F'file=@index.json' https://envs.sh)
            - echo INDEX_URL=$index_url
