matrix:
    VERSION:
        - "3.0.0" # TAG:LATEST
        - "2.15.1"

steps:
    - name: build
      image: woodpeckerci/plugin-docker-buildx
      settings:
          platforms: linux/amd64,linux/arm64/v8
          repo: codeberg.org/${CI_REPO_OWNER}/bird
          registry: codeberg.org
          tags: "${VERSION}"
          build_args:
              - VERSION=${VERSION}
          username: ${CI_REPO_OWNER}
          password:
              from_secret: codeberg_token
          context: services/bird
          dockerfile: services/bird/Containerfile
    - name: mark-latest
      image: alpine
      secrets: [codeberg_token]
      commands:
          - ./scripts/pkgs/tag-latest.sh "codeberg.org/${CI_REPO_OWNER}/bird" .woodpecker/build-bird.yaml "${VERSION}"
    - name: send-ntfy
      image: alpine
      secrets: [ntfy_token]
      environment:
          VERSION: "${VERSION}"
      when:
          - status: [success, failure]
      commands:
          - ./scripts/pkgs/send-log.sh
when:
    - event: push
      branch: main
      path:
          include:
              [".woodpecker/build-bird.yaml", "services/bird/Containerfile"]
    - event: cron
      cron: build-pkgs
    - event: manual
      evaluate: 'TARGET == "all" || TARGET == "bird"'
