steps:
    - name: build-caddy
      image: woodpeckerci/plugin-docker-buildx
      settings:
          platforms: linux/386,linux/amd64,linux/arm64/v8
          repo: codeberg.org/${CI_REPO_OWNER}/x-caddy
          registry: codeberg.org
          tags: latest
          username: ${CI_REPO_OWNER}
          password:
              from_secret: codeberg_token
          dockerfile: caddy/Containerfile
      when:
          - event: push
            path: 'caddy/*'
          - event: cron
            cron: build
          - event: manual
            evaluate: 'BUILD == "caddy"'
