clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0
steps:
  - name: update
    image: alpine
    secrets: [codeberg_token, ntfy_token]
    commands:
      - apk add --no-cache bash curl jq git yq coreutils git-subtree jo \
        php php-calendar php-ctype php-dom php-fileinfo php-iconv php-intl \
        php-xml php-mbstring php-xmlreader composer pnpm
      - ./contrib/updater/update.sh || exit 1
when:
  - event: cron
    cron: update
  - event: manual
    evaluate: 'TARGET == "update"'
