name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: |
            **/build/reports

      - name: Generate report
        uses: gradle/gradle-build-action@v2
        with:
          arguments: run --args="reportAll"

      - name: Remove server jars
        run: rm run/*-server.jar

      - name: Publish to Writee
        if: github.event_name != 'pull_request'
        run: |
          TOKEN=$(curl "https://writee.org/api/auth/login" -H "Content-Type: application/json" -X POST -d '${{ secrets.WRITEE_AUTH }}' | jq .data.access_token -r)
          jo created=$(TZ="Asia/Beijing" date -Iseconds) title=Report body=@summary.md lang=zh slug=$(date -Iseconds -u) > data.json
          RESULT=$(curl "https://writee.org/api/collections/minecraft-server-props-dumper/posts" \
            -H "Content-Type: application/json" -H "Authorization: Token $TOKEN" \
            -X POST -d '@data.json')
          echo $RESULT
          ID=$(echo -E $RESULT | jq .data.id -r)
          curl "https://writee.org/api/collections/minecraft-server-props-dumper/pin" \
            -H "Content-Type: application/json" -H "Authorization: Token $TOKEN" \
            -X POST -d "$(jo $(jo id=$ID position=1) -a)"
          rm data.json

      - uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: run

      - uses: actions/upload-artifact@v3
        with:
          name: summary.ods
          path: run/summary.ods
