name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache
        uses: actions/cache@v3
        with:
          path: run
          key: run

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Generate
        uses: gradle/gradle-build-action@v2
        with:
          arguments: run --args="reportAll"

      - name: Collect Reports
        run: |
          mkdir report
          cp run/*.json report
          cp run/*.ods report

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Reports
          path: report

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Build Artifacts
          path: |
            **/build/reports
