name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: 
      - created

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Upload as Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ./

      - name: Upload Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: ./
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}
        run: npm publish
