name: Push DNS

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "15 */6 * * *"

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check
          config_file: "dns/dnsconfig.js"

      - name: preview
        uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: preview
          config_file: "dns/dnsconfig.js"
          creds_file: "dns/creds.json"

      - name: push
        uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: push
          config_file: "dns/dnsconfig.js"
          creds_file: "dns/creds.json"
